### ISSUE TITLE
pycolmap.Image' object has no attribute 'projection_matrix'

### ISSUE THREAD

**Issue by renhaofan** [QT-Zhu/RPBG#2]
Failed to generate yaml file
```
---------3/3: Start Configuration Generation----------
Traceback (most recent call last):
  File "RPBG/tools/create_yaml.py", line 31, in <module>
    create_yaml()
  File ".conda/envs/RPBG/lib/python3.9/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File ".conda/envs/RPBG/lib/python3.9/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File ".conda/envs/RPBG/lib/python3.9/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File ".conda/envs/RPBG/lib/python3.9/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "RPBG/tools/create_yaml.py", line 9, in create_yaml
    traj = load_colmap(colmap_sparse)
  File "RPBG/tools/pose_format_converter.py", line 199, in load_colmap
    M = image.projection_matrix()
AttributeError: 'pycolmap.Image' object has no attribute 'projection_matrix'
```

**Comment by QT-Zhu** [comment]
Downgrade to v0.4.0, such member has been removed since v0.5.0.
